name: Build and Release Party Pooper

on:
  push:
    paths:
      - package.json

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get version from package.json
        id: version-check
        run: |
          NEW_VERSION=$(jq -r '.version' package.json)
          echo "New version detected: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/PartyPooper-linux-x64
            dist/PartyPooper-win-x64.exe
          tag_name: v${{ steps.version-check.outputs.VERSION }}
          body: ${{ github.event.head_commit.message }}
          name: Party Pooper v${{ steps.version-check.outputs.VERSION }}